# Generated by Django 2.2.13 on 2020-06-11 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, unique=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('client_category', models.CharField(choices=[('Agrochem', 'Agrochem'), ('Construction', 'Construction'), ('Others', 'Others')], max_length=15)),
                ('btc', models.CharField(blank=True, choices=[('Non BTC', 'Non BTC'), ('BTC-1', 'BTC-1'), ('BTC-2', 'BTC-2')], max_length=8)),
                ('telephone_main', models.CharField(blank=True, max_length=15)),
                ('telephone_extra', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('pin_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], default='Maharashtra', max_length=30)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('Overseas', 'Overseas')], default='India', max_length=8)),
                ('client_rank', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('lead_source', models.CharField(choices=[('Reference', 'Reference'), ('Indiamart', 'Indiamart'), ('Others', 'Others')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=2000)),
                ('balance', models.IntegerField(default=0)),
                ('latest_dsr_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_category', models.CharField(choices=[('Agro Chemical', 'Agro Chemical'), ('Defoamer Chemical', 'Defoamer Chemical'), ('Textile Industry Chemical', 'Textile Industry Chemical'), ('Cosmetics Industry Chemical', 'Cosmetics Industry Chemical'), ('Construction Chemical', 'Construction Chemical'), ('Mining Insutry Chemical', 'Mining Insutry Chemical'), ('Paper Insutry Chemical', 'Paper Insutry Chemical'), ('Others', 'Others')], max_length=30)),
                ('hsn_code', models.PositiveIntegerField(null=True)),
                ('basic_rate', models.PositiveIntegerField()),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('export_tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('remarks', models.CharField(blank=True, max_length=2000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(default=django.utils.timezone.now)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('sample_quantity', models.PositiveIntegerField()),
                ('sample_status', models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=8)),
                ('remarks', models.CharField(blank=True, max_length=2000)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('carting', models.PositiveIntegerField(default=0)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('tax_type', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Outside Maharashtra', 'Outside Maharashtra'), ('Indirect Export', 'Indirect Export'), ('Direct Export', 'Direct Export')], max_length=20)),
                ('is_sample', models.BooleanField(default=False)),
                ('total_amount', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField()),
                ('fisrt_date', models.DateField(default=django.utils.timezone.now)),
                ('last_date', models.DateField(default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_received', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Dsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_mode', models.CharField(choices=[('Visit', 'Visit'), ('Telephone', 'Telephone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('No Response', 'No Response'), ('Others', 'Others')], max_length=12)),
                ('date_of_contact', models.DateField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=2000)),
                ('next_call_date', models.DateField()),
                ('sample_status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=8)),
                ('client_rank', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('failed_sale', models.BooleanField(default=False)),
                ('successful_sale', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('igst', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=20)),
                ('export_sale', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Sale')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Product')),
            ],
        ),
    ]
