# Generated by Django 2.2.13 on 2020-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_client_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lead_source',
            field=models.CharField(choices=[('Reference', 'Reference'), ('Indiamart', 'Indiamart'), ('Others', 'Others')], default='Others', max_length=10),
        ),
    ]
