# Generated by Django 2.2.13 on 2020-06-15 00:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_sale_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='basic_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Basic Cost'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='CGST'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='export_sale',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Export Sale'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='IGST'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Sale', verbose_name='Incoice Number'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity Supplied'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='SGST'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Office Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance Amount Remaining'),
        ),
        migrations.AlterField(
            model_name='client',
            name='btc',
            field=models.CharField(blank=True, choices=[('Non BTC', 'Non BTC'), ('BTC-1', 'BTC-1'), ('BTC-2', 'BTC-2')], max_length=8, verbose_name='BTC Category'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_category',
            field=models.CharField(choices=[('Agrochem', 'Agrochem'), ('Construction', 'Construction'), ('Others', 'Others')], max_length=15, verbose_name='Client Category'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_rank',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Client Rank'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Person Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Overseas', 'Overseas')], default='India', max_length=8, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='latest_dsr_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Latest DSR ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead_source',
            field=models.CharField(choices=[('Reference', 'Reference'), ('Indiamart', 'Indiamart'), ('Others', 'Others')], default='Others', max_length=10, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='PIN Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], default='Maharashtra', max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_extra',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telephone Number (Extra)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_main',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zone',
            field=models.CharField(blank=True, choices=[('NORTH', 'NORTH'), ('SOUTH', 'SOUTH'), ('EAST', 'EAST'), ('WEST', 'WEST'), ('CENTRAL', 'CENTRAL'), ('EXPORT', 'EXPORT'), ('NAGPUR', 'NAGPUR')], default='NAGPUR', max_length=8, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='action',
            field=models.CharField(max_length=2000, verbose_name='Action Taken'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='client_rank',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Client Rank'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='contact_mode',
            field=models.CharField(choices=[('Visit', 'Visit'), ('Telephone', 'Telephone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('No Response', 'No Response'), ('Others', 'Others')], max_length=12, verbose_name='Contact Mode'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='date_of_contact',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Contact'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='failed_sale',
            field=models.BooleanField(default=False, verbose_name='Sale Failed'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='next_call_date',
            field=models.DateField(verbose_name='Next Call Date'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='sample_status',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=8, verbose_name='Sample Status'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='successful_sale',
            field=models.BooleanField(default=False, verbose_name='Sale Successful'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_received',
            field=models.PositiveIntegerField(verbose_name='Amount Received'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Sale', verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='basic_rate',
            field=models.PositiveIntegerField(verbose_name='Basic Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='product',
            name='export_tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Export Tax Rate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.PositiveIntegerField(null=True, verbose_name='HSN Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Agro Chemical', 'Agro Chemical'), ('Defoamer Chemical', 'Defoamer Chemical'), ('Textile Industry Chemical', 'Textile Industry Chemical'), ('Cosmetics Industry Chemical', 'Cosmetics Industry Chemical'), ('Construction Chemical', 'Construction Chemical'), ('Mining Insutry Chemical', 'Mining Insutry Chemical'), ('Paper Insutry Chemical', 'Paper Insutry Chemical'), ('Others', 'Others')], max_length=30, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='carting',
            field=models.PositiveIntegerField(default=0, verbose_name='Carting'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='first_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='First Date of Payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='Is this a Sample?'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last Date of Payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remarks',
            field=models.CharField(blank=True, max_length=10, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_type',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Outside Maharashtra', 'Outside Maharashtra'), ('Indirect Export', 'Indirect Export'), ('Direct Export', 'Direct Export')], max_length=20, verbose_name='Tax Type'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity of Sample sent'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=8, verbose_name='Sample Status'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sent_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sample Sent On'),
        ),
    ]
