# Generated by Django 2.2.13 on 2020-06-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200607_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Agro Chemical', 'Agro Chemical'), ('Defoamer Chemical', 'Defoamer Chemical'), ('Textile Industry Chemical', 'Textile Industry Chemical'), ('Cosmetics Industry Chemical', 'Cosmetics Industry Chemical'), ('Construction Chemical', 'Construction Chemical'), ('Mining Insutry Chemical', 'Mining Insutry Chemical'), ('Paper Insutry Chemical', 'Paper Insutry Chemical'), ('Others', 'Others')], max_length=30),
        ),
    ]
