# Generated by Django 2.2.13 on 2020-06-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200607_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latest_dsr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
