# Generated by Django 2.2.13 on 2020-06-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200613_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_by',
        ),
    ]
