# Generated by Django 2.2.13 on 2020-06-07 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200607_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latest_dsr_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
