# Generated by Django 2.2.13 on 2020-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200609_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_category',
            field=models.CharField(choices=[('A', 'Agrochem'), ('C', 'Construction'), ('O', 'Others')], max_length=15),
        ),
    ]
