# Generated by Django 2.2.13 on 2020-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200609_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_category',
            field=models.CharField(choices=[('Agrochem', 'Agrochem'), ('Construction', 'Construction'), ('Others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='contact_mode',
            field=models.CharField(choices=[('Visit', 'Visit'), ('Telephone', 'Telephone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('No Response', 'No Response'), ('Others', 'Others')], max_length=9),
        ),
    ]
