# Generated by Django 2.2.13 on 2020-06-09 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200609_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsr',
            name='contact_mode',
            field=models.CharField(choices=[('Visit', 'Visit'), ('Telephone', 'Telephone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('No Response', 'No Response'), ('Others', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='date_of_contact',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='product_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='data.Product'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='sample_status',
            field=models.CharField(blank=True, choices=[('S', 'Sent'), ('P', 'Pending'), ('O', 'Passed'), ('F', 'Failed')], max_length=1),
        ),
    ]
