# Generated by Django 2.2.13 on 2020-06-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200609_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsr',
            name='sample_status',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=1),
        ),
    ]
