# Generated by Django 2.2.13 on 2020-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200609_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='btc',
            field=models.CharField(blank=True, choices=[('Non BTC', 'Non BTC'), ('BTC-1', 'BTC-1'), ('BTC-2', 'BTC-2')], max_length=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead_source',
            field=models.CharField(choices=[('Reference', 'Reference'), ('Indiamart', 'Indiamart'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='basic_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Dsr',
        ),
    ]
