# Generated by Django 2.2.13 on 2020-06-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200609_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsr',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Product'),
        ),
    ]
