# Generated by Django 2.2.13 on 2020-06-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20200609_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='basic_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.Product'),
        ),
    ]
